Crime.create!([
                  {id: 1, description: "HOMICIDIO"},
                  {id: 2, description: "LESIONES"},
                  {id: 3, description: "AYUDA O INDUCCION AL SUICIDIO"},
                  {id: 4, description: "ABORTO"},
                  {id: 5, description: "PROCREACION ASISTIDA"},
                  {id: 6, description: "INSEMINACION ARTIFICIAL"},
                  {id: 7, description: "MANIPULACION GENETICA"},
                  {id: 8, description: "OMISION DE AUXILIO O DE CUIDADO"},
                  {id: 9, description: "PELIGRO DE CONTAGIO"},
                  {id: 10, description: "PRIVACION DE LA LIBERTAD PERSONAL"},
                  {id: 11, description: "PRIVACION DE LA LIBERTAD CON FINES SEXUALES"},
                  {id: 12, description: "SECUESTRO"},
                  {id: 13, description: "DESAPARICION FORZADA DE PERSONAS"},
                  {id: 14, description: "TRAFICO DE MENORES"},
                  {id: 15, description: "RETENCION Y SUSTRACCION DE PERSONAS MENORES DE EDAD"},
                  {id: 17, description: "ABUSO SEXUAL"},
                  {id: 18, description: "HOSTIGAMIENTO SEXUAL"},
                  {id: 19, description: "ESTUPRO"},
                  {id: 20, description: "INCESTO"},
                  {id: 21, description: "DELITO CONTRA LA FORMACION DE MENORES DE EDAD"},
                  {id: 22, description: "DELITOS CONTRA LA FORMACION DE PERSONAS QUE NO TIENEN CAPACIDAD PARA COMPRENDER EL SIGNIFICADO DEL HECHO"},
                  {id: 23, description: "PORNOGRAFIA CON PERSONAS MENORES DE EDAD"},
                  {id: 24, description: "PORNOGRAFIA CON PERSONAS QUE NO TIENEN CAPACIDAD PARA COMPRENDER EL SIGNIFICADO DEL HECHO"},
                  {id: 25, description: "INCUMPLIMIENTO DE LA OBLIGACION ALIMENTARIA"},
                  {id: 27, description: "ALTERACION DEL ESTADO CIVIL DE LAS PERSONAS"},
                  {id: 28, description: "BIGAMIA"},
                  {id: 29, description: "DELITO CONTRA LA DISCRIMINACION"},
                  {id: 30, description: "TRATA DE PERSONAS"},
                  {id: 31, description: "LENOCINIO"},
                  {id: 32, description: "DELITO DE INHUMACION DE CADAVERES"},
                  {id: 33, description: "DELITO DE EXHUMACION DE CADAVERES O RESTOS HUMANOS"},
                  {id: 34, description: "AMENAZAS"},
                  {id: 35, description: "ALLANAMIENTO DE VIVIENDA, DESPACHO, OFICINA O ESTABLECIMIENTO MERCANTIL"},
                  {id: 36, description: "REVELACION DE SECRETOS"},
                  {id: 37, description: "ROBO"},
                  {id: 38, description: "ROBO DE GANADO"},
                  {id: 39, description: "ROBO DE VEHICULO"},
                  {id: 40, description: "ABUSO DE CONFIANZA"},
                  {id: 41, description: "FRAUDE"},
                  {id: 42, description: "ADMINISTRACION FRAUDULENTA"},
                  {id: 43, description: "INSOLVENCIA FRAUDULENTA EN PERJUICIO DE ACREEDORES"},
                  {id: 44, description: "USURA"},
                  {id: 45, description: "EXTORSION"},
                  {id: 46, description: "DESPOJO"},
                  {id: 47, description: "DAÑOS"},
                  {id: 48, description: "ENCUBRIMIENTO POR RECEPTACION"},
                  {id: 49, description: "DELITO DE OPERACIONES CON RECURSOS DE PROCEDENCIA ILICITA"},
                  {id: 50, description: "ASOCIACION DELICTUOSA"},
                  {id: 51, description: "DELINCUENCIA ORGANIZADA"},
                  {id: 52, description: "ASALTOS"},
                  {id: 53, description: "EJERCICIO ILEGAL ABANDONO DEL SERVICIO PUBLICO"},
                  {id: 54, description: "ABANDONO DEL SERVICIO PUBLICO"},
                  {id: 55, description: "ABUSO DE AUTORIDAD"},
                  {id: 56, description: "USO ILEGAL DE LA FUERZA PUBLICA"},
                  {id: 57, description: "COALISION DE SERVIDORES PUBLICOS"},
                  {id: 58, description: "USO ILEGAL DE ATRIBUCIONES Y FACULTADES"},
                  {id: 59, description: "INTIMIDACION"},
                  {id: 60, description: "NEGACION DEL SERVICIO PUBLICO"},
                  {id: 61, description: "TRAFICO DE INFLUENCIAS"},
                  {id: 62, description: "COHECHO"},
                  {id: 63, description: "PECULADO"},
                  {id: 64, description: "CONCUSION"},
                  {id: 65, description: "ENRIQUECIMIENTO ILICITO COMETIDO POR SERVIDOR PUBLICO"},
                  {id: 66, description: "PROMOCION DE CONDUCTAS ILICITAS"},
                  {id: 67, description: "ENRIQUECIMIENTO ILICITO COMETIDO POR PARTICULAR"},
                  {id: 68, description: "DESOBEDIENCIA DE UN MANDATO DE AUTORIDAD"},
                  {id: 69, description: "RESISTENCIA DE PARTICULARES"},
                  {id: 70, description: "OPOSICION A QUE SE EJECUTE ALGUNA OBRA O TRABAJO PUBLICO"},
                  {id: 71, description: "QUEBRANTAMIENTO DE SELLOS"},
                  {id: 72, description: "ULTRAJES A LA AUTORIDAD"},
                  {id: 73, description: "EJERCICIO ILEGAL DEL PROPIO DERECHO"},
                  {id: 74, description: "USURPACION DE FUNCIONES PUBLICAS"},
                  {id: 75, description: "DENEGACION O RETARDO DE JUSTICIA"},
                  {id: 76, description: "PREVARICACION"},
                  {id: 77, description: "DELITOS EN EL AMBITO DE LA PROCURACION DE JUSTICIA"},
                  {id: 78, description: "TORTURA"},
                  {id: 79, description: "DELITOS EN EL AMBITO DE LA ADMINISTRACION DE JUSTICIA"},
                  {id: 80, description: "OMISION DE INFORMES MEDICO-FORENSES"},
                  {id: 81, description: "DELITOS COMETIDOS EN EL AMBITO DE LA EJECUCION PENAL"},
                  {id: 82, description: "EVASION DE PRESOS"},
                  {id: 83, description: "FRAUDE PROCESAL"},
                  {id: 84, description: "FALSEDAD ANTE AUTORIDAD"},
                  {id: 85, description: "VARIACION DEL NOMBRE O DOMICILIO"},
                  {id: 86, description: "SIMULACION DE PRUEBAS"},
                  {id: 87, description: "DELITOS DE ABOGADOS, PATRONOS Y LITIGANTES"},
                  {id: 88, description: "ENCUBRIMIENTO POR FAVORECIMIENTO"},
                  {id: 89, description: "RESPONSABILIDAD PROFESIONAL Y TECNICA"},
                  {id: 90, description: "USURPACION DE PROFESION"},
                  {id: 91, description: "PRACTICA INDEBIDA DEL SERVICIO MEDICO"},
                  {id: 92, description: "RESPONSABILIDAD DE PERSONAL DE CENTROS DE SALUD Y ESTABLECIMIENTOS FUNERARIOS"},
                  {id: 93, description: "SUMINISTRO DE MEDICINAS NOCIVAS O INAPROPIADAS"},
                  {id: 94, description: "ATAQUES A LAS VIAS DE COMUNICACION"},
                  {id: 95, description: "ATAQUES A LOS MEDIOS DE TRANSPORTE"},
                  {id: 96, description: "VIOLACION DE CORRESPONDENCIA"},
                  {id: 97, description: "VIOLACION DE LA COMUNICACIÓN PRIVADA"},
                  {id: 98, description: "FALSIFICACION DE SELLOS, MARCAS, LLAVES Y OTROS"},
                  {id: 99, description: "ELABORACION O ALTERACION DE USO INDEBIDO DE PLACAS, ENGOMADOS Y DOCUMENTOS DE IDENTIFICACION DE VEHICULOS"},
                  {id: 100, description: "FALSIFICACION O ALTERACION Y USO INDEBIDO DE DOCUMENTOS"},
                  {id: 101, description: "COMETIDOS POR SERVIDORES PUBLICOS"},
                  {id: 102, description: "COMETIDOS POR PARTICULARES"},
                  {id: 103, description: "POR FUNCIONARIOS ELECTORALES"},
                  {id: 104, description: "POR FUNCIONARIO PARTIDISTA"},
                  {id: 105, description: "REBELION"},
                  {id: 106, description: "ATAQUES A LA PAZ PUBLICA"},
                  {id: 107, description: "SABOTAJE"},
                  {id: 108, description: "MOTIN"},
                  {id: 109, description: "SEDICION"},
                  {id: 110, description: "DELITOS ELECTORALES"},
                  {id: 112, description: "ROBO DE AUTOPARTES O ACCESORIOS"},
                  {id: 135, description: "USO Y ACCESO ILICITO A LOS SISTEMAS Y EQUIPOS INFORMATICOS Y DE COMUNICACION"},
                  {id: 111, description: "SUICIDIO (HECHO NO DELICTIVO)"},
                  {id: 114, description: "MUERTE ACCIDENTAL (HECHO NO DELICTIVO)"},
                  {id: 115, description: "MUERTE NATURAL (HECHO NO DELICTIVO)"},
                  {id: 16, description: "VIOLACION"},
                  {id: 26, description: "VIOLENCIA FAMILIAR"},
                  {id: 133, description: "VEHICULO ROBADO - CONDUCTAS ESTABLECIDAS EN EL ART. 212 BIS."},
                  {id: 120, description: "PORTACION DE ARMA DE FUEGO"},
                  {id: 121, description: "PORTACION DE CARTUCHOS"},
                  {id: 122, description: "INTRODUCCION AL PAIS DE ARMAS DE FUEGO"},
                  {id: 123, description: "INTRODUCCION AL PAIS DE CARTUCHOS"},
                  {id: 124, description: "ACOPIO DE ARMAS"},
                  {id: 125, description: "FABRICACION DE ARMAS"},
                  {id: 126, description: "COMPRA DE EXPLOSIVOS"},
                  {id: 127, description: "TRANSPORTE DE EXPLOSIVOS"},
                  {id: 128, description: "ALMACENAMIENTO DE EXPLOSIVOS"},
                  {id: 129, description: "FABRICACION DE EXPLOSIVOS"},
                  {id: 130, description: "CONTRA LA SALUD"},
                  {id: 131, description: "DELITOS AMBIENTALES"},
                  {id: 132, description: "USO DE MONEDA FALSA"},
                  {id: 113, description: "TRATA DE PERSONAS DE INDOLE SEXUAL"},
                  {id: 116, description: "ROBO AGROPECUARIO"},
                  {id: 117, description: "FRAUDE AGROPECUARIO"},
                  {id: 134, description: "DELITOS CONTRA EL DESARROLLO ZOOSANITARIO"},
                  {id: 10000, description: "HOMICIDIO EN TENTATIVA"},
                  {id: 10020, description: "DELINCUENCIA ORGANIZADA"},
                  {id: 10040, description: "NARCOMENUDEO"}
              ])
