Place.create!([
  {description: "No especificado"},
  {description: "Abarrotes"},
  {description: "Aeropuerto"},
  {description: "Agencia de vehículos"},
  {description: "Agencia de viajes"},
  {description: "Alarmas"},
  {description: "Banco - cajero automático"},
  {description: "Banco - oficina mayor"},
  {description: "Banco - sucursal o mini banco"},
  {description: "Bar o cantina"},
  {description: "Basurero"},
  {description: "Bodega"},
  {description: "Brecha / terracería"},
  {description: "Cafetería"},
  {description: "Campo menonita"},
  {description: "Carretera"},
  {description: "Casa de cambio"},
  {description: "Casa habitación"},
  {description: "Celulares"},
  {description: "Central camionera"},
  {description: "Centro cultural"},
  {description: "Centro de copiado"},
  {description: "Centro deportivo"},
  {description: "Centro penitenciario (CERESO-cárcel)"},
  {description: "Cerrajería"},
  {description: "Computadoras / equipo de computo"},
  {description: "Comunicaciones"},
  {description: "Comunidad indígena"},
  {description: "Comunidad mormona"},
  {description: "Constructora"},
  {description: "Consultorio medico"},
  {description: "Desponchado"},
  {description: "Discoteca"},
  {description: "Ejido"},
  {description: "Embotelladora"},
  {description: "Escuela particular"},
  {description: "Escuela pública"},
  {description: "Estación de ferrocarril"},
  {description: "Estacionamiento público"},
  {description: "Farmacia"},
  {description: "Ferretería"},
  {description: "Florería / regalos"},
  {description: "Gasera"},
  {description: "Gasolinera"},
  {description: "Guardería"},
  {description: "Herrería, taller de"},
  {description: "Hospital"},
  {description: "Hotel"},
  {description: "Iglesia"},
  {description: "Imprenta"},
  {description: "Inmobiliaria"},
  {description: "Joyería / relojería"},
  {description: "Laboratorio"},
  {description: "Lavandería"},
  {description: "Llantera"},
  {description: "Lote venta vehículos"},
  {description: "Maderera"},
  {description: "Maquiladora / fábrica"},
  {description: "Mercado público"},
  {description: "Mini súper"},
  {description: "Mueblería"},
  {description: "Negocio (otros)"},
  {description: "Notaría"},
  {description: "Oficina privada"},
  {description: "Oficina pública"},
  {description: "Óptica"},
  {description: "Panteón o cementerio"},
  {description: "Papelería"},
  {description: "Parque, plaza pública"},
  {description: "Peluquería / estilistas"},
  {description: "Pinturas"},
  {description: "Presa, lago o laguna"},
  {description: "Puesto de comida"},
  {description: "Ranchería / localidad rural"},
  {description: "Rancho / huerta privada"},
  {description: "Refaccionaria"},
  {description: "Restaurante (grande)"},
  {description: "Restaurante autoservicio"},
  {description: "Ropa"},
  {description: "Salón de eventos"},
  {description: "Supermercado"},
  {description: "Taller"},
  {description: "Terreno baldío / tapias"},
  {description: "Tortillería"},
  {description: "Transportes"},
  {description: "Vecindad"},
  {description: "Vía pública (calles, avenidas, etc.)"},
  {description: "Vías de ferrocarril"},
  {description: "Videoclub / renta de videos"},
  {description: "Vinos y licores"},
  {description: "Yonke / partes usadas / chatarra"},
  {description: "Zapatería"},
  {description: "Zona rural (otros)"},
  {description: "Zona urbana (lugar público, otros)"},
  {description: "Rancho o Huerta Privados"},
  {description: "Refaccionarias"},
  {description: "Restaurante (Grande)"},
  {description: "Restaurante Autoservicio"},
  {description: "Ropa"},
  {description: "Funeraria"},
  {description: "Rio / Arrollo"}
])
