Status.create!([
                   {id: 10000, description: "DETENIDO", status_type: "persona"},
                   {id: 10001, description: "VICTIMA", status_type: "persona"},
                   {id: 10002, description: "SOSPECHOSO", status_type: "persona"},
                   {id: 10020, description: "PRELIMINAR", status_type: "evento"},
                   {id: 10021, description: "PENDIENTE", status_type: "evento"},
                   {id: 10022, description: "EN PROCESO", status_type: "evento"},
                   {id: 10023, description: "TERMINADO", status_type: "evento"},
                   {id: 10024, description: "HEMEROTECA", status_type: "evento"},
                   {id: 10040, description: "TESTIGO", status_type: "persona"},
                   {id: 10041, description: "SOLICITADO", status_type: "persona"},
                   {id: 10060, description: "PRELIMINAR TERMINADO", status_type: "evento"},
                   {id: 10061, description: "CONTESTADO", status_type: "Colaboracion"},
                   {id: 10080, description: "RECIBIDO", status_type: "Justici@.NET"},
                   {id: 10081, description: "ASIGNADO", status_type: "Justici@.NET"},
                   {id: 10082, description: "FINALIZADO", status_type: "Justici@.NET"},
                   {id: 10025, description: "DESCONOCIDO", status_type: "persona"},
                   {id: 10026, description: "IMPUTADO IDENTIFICADO", status_type: "persona"},
                   {id: 10003, description: "TERMINADO", status_type: "Colaboracion"},
                   {id: 10004, description: "RECIBIDO", status_type: "Colaboracion"},
                   {id: 10005, description: "ASIGNADO", status_type: "Colaboracion"},
                   {id: 10006, description: "ENVIADO", status_type: "Colaboracion"},
                   {id: 10007, description: "APROBADO", status_type: "Colaboracion"}
               ])
